In [23]:
#coloca o path raiz do projeto
working_path = "/home/thierry/Documents/thierry/"

In [24]:
import pandas as pd
import datetime

In [25]:
data = pd.read_csv("/home/thierry/Documents/thierry/data/user4.csv")

In [26]:
for i in range(len(data)):
    data['date'][i] = datetime.datetime.strptime(data['date'][i], '%a %b %d %H:%M:%S GMT-03:00 %Y').day

/home/thierry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [27]:
data['index'] = range(0, len(data))
data = data.query('date < 3 or date > 28')
data

,latitude,longitude,altitude,accuracy,provider,speed,timestamp,date,temperature,humidity,light,proximity,pressure,screen,audio,voluntary_id,index
304,-7.255308,-35.911276,0.0,56.100,fused,0.0,1567047600459,29,0.0,0.0,0.0,0.0,0.0,False,Normal,18,304
305,-7.255308,-35.911276,0.0,56.100,fused,0.0,1567047615681,29,0.0,0.0,0.0,0.0,0.0,False,Normal,18,305
306,-7.255308,-35.911276,0.0,56.100,fused,0.0,1567047630642,29,0.0,0.0,0.0,0.0,0.0,False,Normal,18,306
307,-7.255308,-35.911276,0.0,56.100,fused,0.0,1567047646021,29,0.0,0.0,0.0,0.0,0.0,False,Normal,18,307
308,-7.255271,-35.911105,0.0,17.800,fused,0.0,1567047660880,29,0.0,0.0,0.0,0.0,0.0,False,Normal,18,308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16397,-7.255421,-35.911021,0.0,54.141,fused,0.0,1567479461778,2,0.0,0.0,0.0,8.0,0.0,True,Normal,18,16397
16398,-7.255346,-35.911054,0.0,28.266,fused,0.0,1567479491742,2,0.0,0.0,0.0,8.0,0.0,True,Normal,18,16398
16399,-7.255308,-35.911276,0.0,39.560,fused,0.0,1567479522707,2,0.0,0.0,0.0,8.0,0.0,True,Normal,18,16399
16400,-7.255308,-35.911276,0.0,42.025,fused,0.0,1567479552771,2,0.0,0.0,0.0,8.0,0.0,True,Normal,18,16400
16401,-7.255308,-35.911276,0.0,44.660,fused,0.0,1567479582779,2,0.0,0.0,0.0,8.0,0.0,True,Normal,18,16401

In [28]:
def group_data(df,grouping,column):
    dfg = df
    for i in dfg.index.values:
        dfg['index'][i] = int(i/grouping)
    return dfg.groupby('index')[column].mean()

In [29]:
datag30s = group_data(data,2,'temperature')
datag60s =  group_data(data,4,'temperature')
datag120s =  group_data(data,8,'temperature')

/home/thierry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [30]:
data30s = data.iloc[ 0::2 , : ]
data60s = data.iloc[ 0::4 , : ]
data120s = data.iloc[ 0::8 , : ]

In [31]:
error= 0
count = 0
for i in data30s.index.values:
    error += abs(data30s['temperature'][i] - datag30s.values[count])
    count+=1
print("MÃ©dia erro", error/count)

MÃ©dia erro 0.0

In [32]:
error= 0
count = 0
for i in data60s.index.values:
    error += abs(data60s['temperature'][i] - datag60s.values[count])
    count+=1
print("MÃ©dia erro", error/count)

MÃ©dia erro 0.0

In [33]:
error= 0
count = 0
for i in data120s.index.values:
    error += abs(data120s['temperature'][i] - datag120s.values[count])
    count+=1
print("MÃ©dia erro", error/count)

MÃ©dia erro 0.0