# Find Clusters

In [1]:
#coloca o path raiz do projeto
working_path = "/home/thierry/Documents/thierry/"

In [2]:
import pandas as pd
import os
os.chdir(working_path)

from src.data_processment.stop_region_thierry import MovingCentroidStopRegionFinder

In [159]:
data = pd.read_csv("/home/thierry/Documents/thierry/data/0b2b9de31dfcb837.csv")

In [160]:
import datetime

for i in range(len(data)):
    data['date'][i] = datetime.datetime.strptime(data['date'][i], '%a %b %d %H:%M:%S GMT-03:00 %Y').day

data

/home/thierry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,latitude,longitude,altitude,accuracy,provider,speed,timestamp,date,temperature,humidity,light,proximity,pressure,screen,audio,voluntary_id
0,-7.255347,-35.911039,0.000000,23.476,fused,0.0,1566781277839,25,0.0,0.0,0.0,5.000305,0.0,False,Normal,12
1,-7.255234,-35.910971,0.000000,37.265,fused,0.0,1566781308952,25,0.0,0.0,0.0,5.000305,0.0,True,Normal,12
2,-7.255234,-35.910971,0.000000,42.025,fused,0.0,1566781325109,25,0.0,0.0,0.0,5.000305,0.0,True,Normal,12
3,-7.257795,-35.910951,0.000000,699.999,fused,0.0,1566781355015,25,0.0,0.0,0.0,5.000305,0.0,True,Normal,12
4,-7.255307,-35.911276,510.600006,39.560,fused,0.0,1566781370091,25,0.0,0.0,0.0,5.000305,0.0,True,Normal,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14839,-7.250728,-35.917420,0.000000,2099.999,fused,0.0,1569022034874,20,0.0,0.0,25.0,5.000305,0.0,False,Normal,12
14840,-7.250728,-35.917420,0.000000,2099.999,fused,0.0,1569022206126,20,0.0,0.0,25.0,5.000305,0.0,False,Normal,12
14841,-7.250728,-35.917420,0.000000,2099.999,fused,0.0,1569022340997,20,0.0,0.0,25.0,5.000305,0.0,False,Normal,12
14842,-7.255205,-35.912985,0.000000,72.900,fused,0.0,1568786125970,18,0.0,0.0,39.0,5.000305,0.0,False,Normal,12
14843,-7.255205,-35.912985,0.000000,72.900,fused,0.0,1568786313330,18,0.0,0.0,39.0,5.000305,0.0,False,Normal,12

In [161]:
data = data.query('date < 3 or date > 28')
newData = data.iloc[ 0::8 , : ]
newData

,latitude,longitude,altitude,accuracy,provider,speed,timestamp,date,temperature,humidity,light,proximity,pressure,screen,audio,voluntary_id
281,-7.255000,-35.913102,0.0,68.400,fused,0.0,1567054467911,29,0.0,0.0,53.0,5.000305,0.0,True,Normal,12
289,-7.254980,-35.913096,0.0,68.400,fused,0.0,1567054589593,29,0.0,0.0,53.0,5.000305,0.0,True,Normal,12
297,-7.254980,-35.913096,0.0,88.088,fused,0.0,1567054712062,29,0.0,0.0,50.0,5.000305,0.0,True,Normal,12
305,-7.255205,-35.912986,0.0,64.099,fused,0.0,1567054832289,29,0.0,0.0,47.0,5.000305,0.0,True,Normal,12
313,-7.254980,-35.913096,0.0,64.099,fused,0.0,1567054952776,29,0.0,0.0,47.0,5.000305,0.0,True,Normal,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8281,-7.254912,-35.912871,0.0,52.400,fused,0.0,1567464058905,2,0.0,0.0,5.0,5.000305,0.0,True,Normal,12
8289,-7.254912,-35.912871,0.0,52.400,fused,0.0,1567464179180,2,0.0,0.0,5.0,5.000305,0.0,True,Normal,12
8297,-7.254410,-35.907887,0.0,2700.000,fused,0.0,1567464301197,2,0.0,0.0,8.0,5.000305,0.0,True,Normal,12
8305,-7.254410,-35.907887,0.0,2700.000,fused,0.0,1567464421500,2,0.0,0.0,5.0,5.000305,0.0,True,Normal,12
8313,-7.254410,-35.907887,0.0,2700.000,fused,0.0,1567464541756,2,0.0,0.0,5.0,5.000305,0.0,True,Normal,12

In [162]:
def timestamp_from_mili_to_seconds(milisseconds):
    return milisseconds / 1000

In [163]:
#r Ã© o raio mÃ¡ximo que um ponto (lat, lon) pode assumir para compor uma Stop Region, Ã© em metros
#delta_t Ã© o intervalo de tempo  mÃ­nimo que pracisa para formar uma Stop Region

def find_clusters(user_data, r, delta_t):
    r = 500
    delta_t = 300

    if len(user_data) == 0:
        print("User data is empty")
        return

    print("FINDING STOP REGIONS")
    stop_region_finder = MovingCentroidStopRegionFinder(region_radius=r, delta_time=delta_t)

    clusters = stop_region_finder.find_clusters(user_data, verbose=False)
    print(len(clusters), "found")

    return clusters

In [164]:
newData["local_time"] = timestamp_from_mili_to_seconds(data["timestamp"])

/home/thierry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [165]:
clusters = find_clusters(newData, r=500, delta_t=5*60)

FINDING STOP REGIONS
99 found

In [126]:
#Cada cluster eh uma Stop Region